# Generated by Django 6.0.6 on 2026-06-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasb', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('dev_long', models.CharField(max_length=200)),
                ('frameworks', models.CharField(max_length=200)),
                ('database', models.CharField(max_length=200)),
                ('frontend_t', models.CharField(max_length=200)),
                ('python_modul', models.CharField(max_length=200)),
                ('ish_joy', models.CharField(max_length=200)),
                ('lavozim', models.CharField(max_length=200)),
                ('vazifalar', models.CharField(max_length=200)),
                ('ishlash_davri', models.CharField(max_length=200)),
                ('yutuq_rasm', models.ImageField(upload_to='media/photos')),
                ('yutuq_info', models.CharField(max_length=200)),
                ('life_long', models.CharField(max_length=200)),
            ],
        ),
    ]
