# Generated by Django 6.0.6 on 2026-06-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_resume_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/photos')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
