# Generated by Django 6.0.6 on 2026-06-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_resume_app', '0002_about_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='ish_joy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='ishlash_davri',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='lavozim',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='vazifalar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
