# Generated by Django 6.0.6 on 2026-06-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_resume_app', '0003_alter_resume_ish_joy_alter_resume_ishlash_davri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='yutuq_info',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='yutuq_rasm',
        ),
    ]
