# Generated by Django 6.0.6 on 2026-06-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_logo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/logo')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
